apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-game
spec:
  selector:
    matchLabels:
      app: pokedex-game
  template:
    metadata:
      labels:
        app: pokedex-game
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: pokedex-game
        image: nvtdemo.azurecr.io/pokedex-game:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-game-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pokedex-game
